### ISSUE TITLE
mb-config.json

### ISSUE THREAD

**Issue by deezone** [DoSomething/quicksilver-config#9]
Add `mb_config.json` to repo based on current version in `messagebroker-config`: https://github.com/DoSomething/messagebroker-config/blob/master/mb_config.json

**Comment by sergiitk** [comment]
It might make sense to provide it in Docker volume. Let's try the volume first so we don't have not maintain two `mb_config.json` version.

**Comment by sergiitk** [comment]
Ok, I researched using Docker volumes in wercker and it's not as good as I thought. Let's get back to the original idea and just include a copy of `mb_config.json` in this repo.

Keeping in mind that at some point this will be the master version of the configuration.

cc @mshmsh5000
